### PR TITLE
Update Etsy's leave policy

### PR DESCRIPTION
**Pull request by april**

### CODE REVIEW

**Comment by davedash** [comment]
yay!  Thanks

**Comment by april** [comment]
Agreed!  Hopefully it becomes a standard policy across every company.  :)

**Comment by davedash** [comment]
Wow... the two years to use 18 weeks of the leave is amazing.  My youngest isn't even two years old and he's a DELIGHT right now, I'd have loved to have that kind of flexibility.

**Comment by april** [comment]
I think it’s very common in many countries. My kid is three years old and I agree there were many times over the first couple years where I wish I hadn’t had to dig into my PTO to take care of a sick kid, or take him to appointments.  Boo @ US.

**Pull request merged**
